### ISSUE TITLE
Implement

### ISSUE THREAD

**Issue by kentcdodds** [formly-js/formly-builder#1]
Build this thing with awesomeness.

**Comment by sduquej** [comment]
Hey @kentcdodds!
I'd like to get this built, but would probably need to bother you with some questions. For starters, is the [angular-form-builder](https://github.com/kelp404/angular-form-builder) still similar to what you have in mind for this?

**Comment by kentcdodds** [comment]
Hi @sduquej! This would be totally awesome if you could build it! The world would thank you for it! You can totally ask me anything you need to help you build this. Here are some requirements:
- Ability to select a template library to use (Bootstrap, vanilla, LumX, Ionic, angular-material, etc.)
- Drag-and-drop capabilities (like angular-form-builder)
- Specify custom types and wrappers (probably some sort of CodeMirror input or something) - This one could be a little bit of a challenge...
- Preview the output form and interact with it
- Output the fields configuration

This wont be a small task I think, but if you're able to do it, it will make people's lives so much easier. I'd really appreciate it.

As far as project decisions, it's all up to you. I recommend you try building this with webpack using babel for ES6. That's how angular-formly is built and it's just totally awesome. If you want an example of how this is done, the demo part of formly is built with webpack and ES6: https://github.com/formly-js/angular-formly/tree/master/demo

Thanks again for your willingness! Let me know if you have any questions on Gitter: https://gitter.im/formly-js/angular-formly

**Comment by jasonrichardsmith** [comment]
Is this still being worked on?

**Comment by kentcdodds** [comment]
Good question. I'm not currently able to work on it... Would love it if someone were able to...

**Comment by sduquej** [comment]
I didn't get far enough on this and it's been a while since I last worked on it... 
I haven't checked, but am not sure if the current version of formly would work with what I have, which was a fork of [this](https://github.com/kelp404/angular-form-builder) project modified to support the formly-bootstrap fields.

So no, sorry. I'm no longer working on this :(
